### ISSUE TITLE
変換の準備に失敗してしまう

### ISSUE THREAD

**Issue by fhrk-78** [rojiroji/disnote#5]
こんにちは、プログラミングは全くと言っていいほど知らない動画編集者です
DisNOTEを使わせていただいたのですが、どうも変換に失敗してしまうのでお願いします。

子プロセスがコード4294967295で終了しました？のような文章だったので終了コード4294967295を調べてみましたが
WSLの事が多く出てきました。関連性を探すことは私の知識では不可能でした。
どうか解決策か、修正をお待ちしております。
## 行った動作
- Craigで録音してDiscordのボイストークを行った
- Craigのダウンロードを行った（Other formats > Multi-track smart-leveled > FLAC）
- 解凍したファイルをGUIにドラッグ&ドロップした
## もしかしたら干渉しているかもしれない候補
昔インストールしたプログラミング関係です
- Node.js 18.15.0 (17.1.0・8.10.0)
- Python 3.10
- Oracle Java 8
- Windows Subsystem for Linux
- git (windows v2.39.0)
- GNU Win32
- .NET SDK系のバージョンは確認できませんでした
## disnote_gui.log の内容
```
[2023-11-07T15:44:00.207] [INFO] system - DisNote GUI
[2023-11-07T15:45:22.439] [INFO] system - Child process exited with code 4294967295 / projectId = 0
[2023-11-07T15:45:29.497] [INFO] system - Child process exited with code 4294967295 / projectId = 0
[2023-11-07T15:45:33.900] [INFO] system - Child process exited with code 4294967295 / projectId = 0
[2023-11-07T15:46:37.552] [INFO] system - DisNote GUI:exit.
```
違うファイル（同じくFLAC形式）で試した
```
[2023-11-07T15:46:39.651] [INFO] system - DisNote GUI
[2023-11-07T15:47:01.620] [INFO] system - Child process exited with code 4294967295 / projectId = 0
[2023-11-07T15:49:56.948] [INFO] system - Child process exited with code 4294967295 / projectId = 1
[2023-11-07T15:50:01.437] [INFO] system - DisNote GUI:exit.
```
追加情報がございましたら即急に補足いたしますのでよろしくお願いします

書き忘れていました、スペック面です
- メモリ：8.00 GB (7.75 GB 使用可能)
- CPU：Intel(R) Pentium(R) Silver J5040 CPU @ 2.00GHz   2.00 GHz 4
- システム：64 ビット オペレーティング システム、x64 ベース プロセッサ
- OS：Windows 11 Home 21H2 ビルド 22000.2538 HP製

**Comment by rojiroji** [comment]
disnote_gui.log と同じフォルダに speechrec.log というファイルがあるはずなので、その内容を貼り付けていただけますか。
最後の方にエラーメッセージのようなものが出ていると思います。

**Comment by fhrk-78** [comment]
@rojiroji 返信ありがとうございます。確認して見ましたが、やはり`disnote_gui.log`しか生成されておりませんでした。

**Comment by fhrk-78** [comment]
書き忘れていました、スペック面です
- メモリ：8.00 GB (7.75 GB 使用可能)
- CPU：Intel(R) Pentium(R) Silver J5040 CPU @ 2.00GHz   2.00 GHz 4
- システム：64 ビット オペレーティング システム、x64 ベース プロセッサ
- OS：Windows 11 Home 21H2 ビルド 22000.2538 HP製

**Comment by fhrk-78** [comment]
[`src/DisNOTE_GUI/js/main.js`](https://github.com/rojiroji/disnote/blob/main/src/DisNOTE_GUI/js/main.js)の`engineClose`関数(404行目)の最後の方の条件分岐でメッセージが出されているように見えます
ただ、ソースコードのreturn文を探し回ったのですが、DisNOTEエンジンのどこが実行結果を返しているのか私には分かりませんでした。申し訳ございません。
## 実際の画面
![スクリーンショット 2023-11-08 153147](https://github.com/rojiroji/disnote/assets/120289597/19ccc236-eb14-4dcc-8194-64642d1d422b)

**Comment by rojiroji** [comment]
情報ありがとうございます。ちょっと原因分析に手こずりそうなので、情報収集にご協力ください。
以下の確認をお願いできますでしょうか。

1. DisNOTE_ForGUI.bat をダブルクリックで実行するとどうなるか
（しばらく待った後に「ファイルが指定されていません」と表示して終了すると正常です）
2. disnote_gui.log と同じフォルダに speechrec.log が作成されているかどうか
3. 作成されていた場合、中身を貼り付けてください
4. DisNOTE.exeと同じフォルダにstderr.txtというファイルが作成されているかどうか
5. 作成されていた場合、中身を貼り付けてください

（補足）
「音声認識開始」ボタンを押すと、内部でDisNOTE_ForGUI.bat を実行するという作りになっています。
DisNOTE_ForGUI.bat が code 4294967295 で異常終了している、というところまではわかっています。
（補足2）
4294967295で検索すると、Windows Subsystem for Linuxに関する記事がいくつか出てきました。
ただ、本当に関係があるかどうかはわかりません。

**Comment by fhrk-78** [comment]
返信ありがとうございます
確認結果は以下となっております
### 1. DisNOTE_ForGUI.batの実行結果
```
>cd /d F:\Programs\DisNOTE_3.2.0\

>dist\all.exe --files   2>stderr.txt
```
そして「ファイルが指定されていません」と表示されずに勝手に消えます
### 2. speechrec.log
`disnote_gui.log`しか存在しませんでした
念の為、dirコマンドの実行結果です
```
2023/11/08  15:55             2,069 disnote_gui.log
               1 個のファイル               2,069 バイト
```
### 4. stderr.txt
こちらは存在しておりました
### 5. stderr.txtファイルの中身
```
[3464] Failed to extract PIL\_imaging.cp39-win_amd64.pyd: decompression resulted in return code -1!
```

**Comment by fhrk-78** [comment]
## 管理者権限
「管理者として実行」でDisNOTEのWhisperを使いました。しかし、そちらでもうまく行きませんでした

もしかしたらと思い再インストールしてみました
## 変更点
- 再インストールした
- 関係ないかもしれませんがディレクトリを固定ドライブに移した

以上の2つです
## 結果
Whisperを使うとまた先程の様にエラーが起きてしまいます
しかしGoogle+Wit.ai...等ならば _**「無事に字幕を出力できました」**_
なぜかは分かりませんでした

**Comment by rojiroji** [comment]
情報ありがとうございます。
speechrec.log が出力されない原因はまだわかりませんが、再インストールか固定ドライブへの移動で改善された可能性があります。

Google+Wit.aiで成功した（Whisperを使うと失敗する）件については別の原因で、DisNOTEのバグでした。すみません。
先ほど修正版を公開しました。

**Comment by fhrk-78** [comment]
返信ありがとうございます
v.3.2.1をインストールしました、しかし、Whisperは使えませんでしたWit.aiとGoogleだけでも謎のコード4294967295で終了してしまいました... speechrec.logは同じく生成されていないです

**Comment by rojiroji** [comment]
最初の現象に戻ってしまいましたね。
v3.2.0は再インストールか固定ドライブへの移動で改善されたので、もう1回同じことをやってみるとかでしょうか。

DisNOTE_ForGUI.batを直接起動しても speechrec.logが出力されないことから、何かしらの原因でそもそもエンジンが起動していないようです。
DisNOTE_ForGUI.batは、中でさらに dist\all.exe を起動します。 speechrec.logを出力するのは all.exe です。
これがWindowsやセキュリティ対策ソフトで起動をブロックされている可能性があります。
all.exeを直接実行するとどうでしょう。ダブルクリックではなく、コマンドプロンプトから実行してみてください。

**Comment by fhrk-78** [comment]
引数がなにか必要なのでしょうか...?
![スクリーンショット 2023-11-12 100627](https://github.com/rojiroji/disnote/assets/120289597/fc5245f3-ec48-4981-b7d1-7742457cf9c9)

**Comment by rojiroji** [comment]
引数チェックの前にエラーで落ちていますね。
all.exeは、pythonで組んだコードからpyinstallerというツールで実行ファイルに変換したものです。

起動時に、自動的に中身を解凍(extract)してから実行しているようなのですが、ここでエラーになっています。
管理者権限で実行しているようですし、何かと競合しているか、ディスクの空きがないか…。
ただ、Python 3.10とは競合していないはずです。

**Comment by fhrk-78** [comment]
ディスクに空き容量が全くなかったので4GB空けてみました、すると違うエラー(コード1)が発生しました

**Comment by rojiroji** [comment]
了解です。コード1であれば、 speechrec.log が出力されている可能性が高いです。確認してみていただけますか。

**Comment by fhrk-78** [comment]
すみません、普通にできました...
![スクリーンショット 2023-11-18 175249](https://github.com/rojiroji/disnote/assets/120289597/ed580460-e061-4fd5-bc50-f2c2e7505399)

**Comment by rojiroji** [comment]
了解しました。ディスクサイズは要注意ですね。サイトに注意書きを書いておきます。
